CC=gcc
INCLUDES=-I./include
CFLAGS:=-O0 -Wall -Wextra $(INCLUDES)
DEBUG_CFLAGS:=-DDEBUG -g3

TARGET=main.exe

SRC_DIR=src
HEADER_DIR=include

SOURCES=$(wildcard $(SRC_DIR)/*.c)
HEADERS=$(wildcard $(HEADER_DIR)/*.h)

build: $(SOURCES) $(HEADERS)
	$(CC) $(CFLAGS) $(SOURCES) -o $(TARGET)

clean:
	del $(TARGET)

.PHONY: build clean